[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[font]
normal = { family = "FiraCode Nerd Font Mono" }
size = 12

[window]
dimensions = { columns = 90, lines = 25 }
